// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdGY18FXV5rRt-HqFFsi9DTsHzlfv84SA',
    appId: '1:603919049610:android:713510fd3e2581416fde73',
    messagingSenderId: '603919049610',
    projectId: 'weavers-dev',
    databaseURL: 'https://weavers-dev-default-rtdb.firebaseio.com',
    storageBucket: 'weavers-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4R0TiY-cvgD4X6MC79Is6yegX-S1CymA',
    appId: '1:603919049610:ios:3d02f4aed813aad86fde73',
    messagingSenderId: '603919049610',
    projectId: 'weavers-dev',
    databaseURL: 'https://weavers-dev-default-rtdb.firebaseio.com',
    storageBucket: 'weavers-dev.firebasestorage.app',
    androidClientId: '603919049610-msocksel9097supanj2a5eh3bj75amkt.apps.googleusercontent.com',
    iosClientId: '603919049610-3kar3p2ovha4cht0urpcmcifhp6ium9u.apps.googleusercontent.com',
    iosBundleId: 'weavers.dev.app',
  );

}